### PR TITLE
feat: Image Preview Improvements

### PR DESCRIPTION
**Pull request by dthyresson**
This PR makes several improvements to the OG Tag preview:

1. Adds an imageUrl to the post
2. Adds image url seed data for post

Also:

1. More validation of values (dates, urls)
3. Allows no image url
4. show empty preview if validation errors
5. shows hostname vs url in preview 
6. formats dates and times
7. corrects some seed data to show 1 sentence description 
8. fakes some errors for posts 2 and 3 for demo of validation errors
9. adds error message to the result
10. adds performance timings around fetch

image

image

image

image

image

### CODE REVIEW

**Comment by dthyresson** [comment]
Should total time be ... renamed?

**Comment by dthyresson** [comment]
@Tobbe  This is the code from the Town Hall demo ... with the addition of the Performance Timing idea we discussed. Total time is probably not the correct name, so open to suggestions.

**Comment by Tobbe** [comment]
These metrics all look great, but I wonder if we should actually show them
image

Is there anything you (as a developer) can do to influence Time To First Byte in the context of OG Tags?
If the only number you have any control over is the last one, Total Time, I think that's the only one we should show

**Comment by dthyresson** [comment]
> These metrics all look great, but I wonder if we should actually show them image
> 
> Is there anything you (as a developer) can do to influence Time To First Byte in the context of OG Tags? If the only number you have any control over is the last one, Total Time, I think that's the only one we should show

Good point. The "total" is anything that will occur whilst rendering the page (Render time?) and that includes work to create the Metadata (say image generation or what not) and general "paint".

**Comment by Tobbe** [comment]
Instead of Total Time, what about Execution Time? This is all in the context of OG Tags, and it's the total time it took to execute the OG generation, right?

**Comment by dthyresson** [comment]
> Instead of Total Time, what about Execution Time? This is all in the context of OG Tags, and it's the total time it took to execute the OG generation, right?

Right. And really that's closest to:

```
 const lastByteTime = performance.now()
```

1. do the fetch
2. await it
3. make sure get all content

Execution time seems right.

Now, does having a tab and one card make sense. I'll think on it.

**Comment by dthyresson** [comment]
> Instead of Total Time, what about Execution Time? This is all in the context of OG Tags, and it's the total time it took to execute the OG generation, right?

Actually ...

```
// Start timing just before the request is made
  const start = performance.now()

  try {
    const response = await fetch(url, headers)

    // Time after receiving the first byte
    const firstByteTime = performance.now()

    const clone = response.clone()

    // Ensure the body is fully read
    await clone.blob()

    // Time after receiving the last byte
    const lastByteTime = performance.now()
``

firstByteTime = request returns
lastByteTime = request body completed

So, both of these the developer can control -- well, some. If they do "work" to assembled the metadata.

total time = body processed (assuming larger html returning will take longer to process)

So, I think these three numbers are valid.

* request duration
* execution duration
* content processing est.
* maybe html KB size?

**Comment by dthyresson** [comment]
Bytes?

image

**Comment by dthyresson** [comment]
I think I like this

image


If so, I'll rename the SDL type fields and some cleanup.

**Comment by Tobbe** [comment]
I like "Response Size" better than "Response Length"

What does "Request Time" mean?

**Comment by dthyresson** [comment]
> I like "Response Size" better than "Response Length"
> 
> What does "Request Time" mean?

image

Some tooltips:

```ts
        <Stat
          caption="Execution Time"
          metric={metrics.executionTime}
          color="blue"
          tooltip="The time to execute the request"
        />
        <Stat
          caption="Response Time"
          metric={metrics.responseTime}
          color="violet"
          tooltip="The time to receive the complete response body"
        />
        <Stat
          caption="Response Size"
          metric={metrics.responseSize / 1_024.0}
          uom="KB"
          precision={2}
          color="fuchsia"
          tooltip="The size of the complete response in kilobytes"
        />
```

image


My idea is:

* how long to execute the request -- render metadata, render the page body
* how long to process and receive the full body -- this will depend on the size of the body. if 20k, short. if 3mb page ... long.
* and then how large was the full body response type. ie, this number give meaning to response time

* execution - if you do less work in your page, cell to fetch data and/or what you do to generate metadata -- you can influence this
* response - how big his your SSR'd body. you can control this (sort of) to see what the request returns
* size - helps understand why response time might be large

**Review by Tobbe — APPROVED** [review]

**Pull request merged**
